CREATE TYPE "public"."currency" AS ENUM('USD', 'ARS', 'EUR', 'BRL', 'CLP', 'COP', 'MXN', 'PEN', 'UYU');--> statement-breakpoint
CREATE TYPE "public"."property_condition" AS ENUM('NEW', 'USED', 'UNDER_CONSTRUCTION', 'REMODELED', 'TO_REMODEL');--> statement-breakpoint
CREATE TYPE "public"."property_status" AS ENUM('DRAFT', 'ACTIVE', 'PAUSED', 'SOLD', 'RENTED', 'RESERVED', 'INACTIVE');--> statement-breakpoint
CREATE TYPE "public"."property_type" AS ENUM('HOUSE', 'APARTMENT', 'LAND', 'COMMERCIAL', 'OFFICE', 'WAREHOUSE', 'GARAGE', 'BUILDING', 'COUNTRY_HOUSE', 'FARM', 'STUDIO', 'PENTHOUSE', 'DUPLEX', 'TRIPLEX', 'LOFT', 'OTHER');--> statement-breakpoint
CREATE TYPE "public"."transaction_type" AS ENUM('SALE', 'RENT', 'TEMPORARY_RENT');--> statement-breakpoint
CREATE TABLE "property" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"organization_id" uuid NOT NULL,
	"title" varchar(500) NOT NULL,
	"slug" varchar(600) NOT NULL,
	"property_type" "property_type" NOT NULL,
	"transaction_type" "transaction_type" NOT NULL,
	"status" "property_status" DEFAULT 'DRAFT' NOT NULL,
	"internal_code" varchar(100),
	"currency" "currency" DEFAULT 'USD' NOT NULL,
	"price" numeric(15, 2) NOT NULL,
	"previous_price" numeric(15, 2),
	"maintenance_fee" numeric(12, 2),
	"price_per_sqm" numeric(12, 2),
	"description" text,
	"short_description" varchar(1000),
	"private_notes" text,
	"country" varchar(100),
	"state" varchar(100),
	"city" varchar(100),
	"neighborhood" varchar(150),
	"address" varchar(500),
	"street_number" varchar(20),
	"floor" varchar(10),
	"apartment" varchar(20),
	"zip_code" varchar(20),
	"latitude" double precision,
	"longitude" double precision,
	"total_area" numeric(10, 2),
	"covered_area" numeric(10, 2),
	"land_area" numeric(10, 2),
	"bedrooms" integer,
	"bathrooms" integer,
	"half_bathrooms" integer,
	"garages" integer,
	"parking_spaces" integer,
	"stories" integer,
	"year_built" integer,
	"condition" "property_condition",
	"orientation" varchar(50),
	"disposition" varchar(50),
	"has_pool" boolean DEFAULT false,
	"has_garden" boolean DEFAULT false,
	"has_terrace" boolean DEFAULT false,
	"has_balcony" boolean DEFAULT false,
	"has_air_conditioning" boolean DEFAULT false,
	"has_heating" boolean DEFAULT false,
	"has_central_heating" boolean DEFAULT false,
	"has_fireplace" boolean DEFAULT false,
	"has_closets" boolean DEFAULT false,
	"has_laundry_room" boolean DEFAULT false,
	"has_security" boolean DEFAULT false,
	"has_elevator" boolean DEFAULT false,
	"has_gym" boolean DEFAULT false,
	"has_pets_allowed" boolean DEFAULT false,
	"is_furnished" boolean DEFAULT false,
	"has_rooftop" boolean DEFAULT false,
	"has_grill" boolean DEFAULT false,
	"has_solar_panels" boolean DEFAULT false,
	"has_water_tank" boolean DEFAULT false,
	"has_service_room" boolean DEFAULT false,
	"meta_title" varchar(200),
	"meta_description" varchar(500),
	"keywords" text[],
	"video_url" varchar(500),
	"virtual_tour_url" varchar(500),
	"agent_id" uuid,
	"contact_phone" varchar(50),
	"contact_email" varchar(255),
	"contact_whatsapp" varchar(50),
	"is_featured" boolean DEFAULT false NOT NULL,
	"is_published" boolean DEFAULT false NOT NULL,
	"published_at" timestamp,
	"expires_at" timestamp,
	"view_count" integer DEFAULT 0 NOT NULL,
	"deleted" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL,
	"updated_at" timestamp DEFAULT now() NOT NULL,
	CONSTRAINT "property_slug_unique" UNIQUE("slug")
);
--> statement-breakpoint
CREATE TABLE "property_image" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"property_id" uuid NOT NULL,
	"url" varchar(1000) NOT NULL,
	"alt_text" varchar(255),
	"order" integer DEFAULT 0 NOT NULL,
	"is_primary" boolean DEFAULT false NOT NULL,
	"created_at" timestamp DEFAULT now() NOT NULL
);
--> statement-breakpoint
ALTER TABLE "property" ADD CONSTRAINT "property_organization_id_organization_id_fk" FOREIGN KEY ("organization_id") REFERENCES "public"."organization"("id") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "property" ADD CONSTRAINT "property_agent_id_user_id_fk" FOREIGN KEY ("agent_id") REFERENCES "public"."user"("id") ON DELETE set null ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "property_image" ADD CONSTRAINT "property_image_property_id_property_id_fk" FOREIGN KEY ("property_id") REFERENCES "public"."property"("id") ON DELETE cascade ON UPDATE no action;