export enum RejectionReason {
  CLIENT_NOT_QUALIFIED = 'CLIENT_NOT_QUALIFIED',
  INCOMPLETE_DATA = 'INCOMPLETE_DATA',
  BROKER_NOT_ENABLED = 'BROKER_NOT_ENABLED',
  TAKEN_INTERNALLY = 'TAKEN_INTERNALLY',
  OTHER = 'OTHER',
}
