export enum ProjectAmenity {
  POOL = 'POOL',
  GYM = 'GYM',
  ROOFTOP = 'ROOFTOP',
  PLAYGROUND = 'PLAYGROUND',
  BBQ_AREA = 'BBQ_AREA',
  COWORKING = 'COWORKING',
  LOBBY = 'LOBBY',
  SECURITY_24H = 'SECURITY_24H',
  PARKING_VISITORS = 'PARKING_VISITORS',
  PET_FRIENDLY = 'PET_FRIENDLY',
  SMART_HOME = 'SMART_HOME',
}
